### PR TITLE
Introduce client side dependencies to application.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**
- This should provide a working example for the rendering of a basic react component.

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
@clloyd How does this look?

**Comment by cb372** [comment]
I'm not qualified to review this, but I can say that it works! 
I managed to get a Hello World on my machine by running `setup.sh` and `start.sh`.

**Comment by clloyd** [comment]
Looks great to me! :+1:

**Comment by LATaylor-guardian** [comment]
Cheers @clloyd

**Pull request merged**
