### PR TITLE
Fix critical vuln in babbel/traverse

### PR DESCRIPTION
**Pull request by Divs-B**
## What does this change?

New critical vulnerability in the `@babel/traverse` package highlighted by Snyk hence upgraded to 7.23.2 version as recommended.

## How to test

Run local test.
Run snyk test.
Run locally.

## How can we measure success?

Floodgate should work as expected and snyk test should overcome by critical vuln.

### CODE REVIEW

**Review by jonathonherbert — APPROVED** [review]
Looks like it's scoped to CDK, which is exercised in CI, so if it ticks ... I clicks ✅

**Review by jonathonherbert — CHANGES_REQUESTED** [review]
Oh, just spotted that the `yarn.lock` was deleted – we'd expect to check in a revised file. Happy to pair!

**Comment by Divs-B** [comment]
o yes , good spot 
I will quickly check at my end.
Thanks @jonathonherbert

**Review by jonathonherbert — APPROVED** [review]
LGTM!

**Pull request merged**
